### ISSUE TITLE
invalid product links

### ISSUE THREAD

**Issue by EvaTechy** [dvishal485/flipkart-scraper-api#10]
In result of API https://flipkart-scraper-api.dvishal485.workers.dev/search/tv all Product links are invalid

**Comment by UtkarshSingh5474** [comment]
+1, the promoted product results are invalid.

**Comment by EvaTechy** [comment]
If we skip removing PID from link then it will work fine

**Comment by dvishal485** [comment]
> If we skip removing PID from link then it will work fine

Okay, good to know. Will you submit a PR regarding the same?
Here is the required line to be removed/modified:
https://github.com/dvishal485/flipkart-scraper-api/blob/dd37cc1380f302f452cba436473325860df9858b/API/search.js#L171

**Comment by EvaTechy** [comment]
there is one more issue on same API https://flipkart-scraper-api.dvishal485.workers.dev/search/tv product name is invalid
`"result":[{"name":"<span","link":"https://www.flipkart.com/mi-series-100-cm-40-inch-full-hd-led-smart-google-tv/p/itm027b4f1e542d7","current_price":22999,"original_price":29999,"discounted":true,"thumbnail":"https://rukminim2.flixcart.com/image/312/312/xif0q/television/1/k/b/-original-imagrzhydhjyhxtf.jpeg?q=70","query_url":"https://flipkart-scraper-api.dvishal485.workers.dev/product/mi-series-100-cm-40-inch-full-hd-led-smart-google-tv/p/itm027b4f1e542d7"},{"name":"<span","link":"https://www.flipkart.com/mi-series-108-cm-43-inch-full-hd-led-smart-google-tv-bezel-less-design-dolby-audio-2023-model/p/itm5d3f8da36722a","current_price":24999,"original_price":35999,"discounted":true,"thumbnail":"https://rukminim2.flixcart.com/image/312/312/xif0q/television/g/7/u/-original-imagrzhy5er9wqfa.jpeg?q=70","query_url":"https://flipkart-scraper-api.dvishal485.workers.dev/product/mi-series-108-cm-43-inch-full-hd-led-smart-google-tv-bezel-less-design-dolby-audio-2023-model/p/itm5d3f8da36722a"}`



Seems like if products are sponsored then in that case product name coming as a `<span>`

**Comment by dvishal485** [comment]
This should be fixed now. Let me know if the issue still persists.
