### ISSUE TITLE
Some product details are missing (like images, seller info, ...)

### ISSUE THREAD

**Issue by Riken-Shah** [dvishal485/flipkart-scraper-api#2]
Hey @dvishal485, Great Work! 

I really liked your "Flipkart Scraper API" project, but some details are missing like product images, variants, seller information. 

It'd be great if you can add them too.

**Comment by dvishal485** [comment]
Hey @Riken-Shah 👋🏻

Yes, the API is still lacking many vital information.

As of product image, the feature is present in form of thumbnails.

---

## Increasing Resolution of Image

You can increase the resolution of image by changing certain parameters in the thumbnail link.

For example, in the link :
```
https://rukminim2.flixcart.com/image/312/312/kzfvzww0/computer/r/g/i/hp-laptop-15s-eq2144au-amd-ryzen-5-5500u-8gb-ddr4-512-gb-pcie-original-imagbg5jctdf4xwf.jpeg?q=70
```
The _312/312_ describes the resolution. Just change it to _1024/1024_ for product image.

```
https://rukminim2.flixcart.com/image/1024/1024/kzfvzww0/computer/r/g/i/hp-laptop-15s-eq2144au-amd-ryzen-5-5500u-8gb-ddr4-512-gb-pcie-original-imagbg5jctdf4xwf.jpeg?q=70
```

---

Seller information won't be difficult to extract as it is present in every product page. Varient information maybe a tricky to extract.

But both are obviously possible to obtain! I will try to add it but may take a while due to busy schedule. But if you can add these features, then PR is always welcome!

**Comment by Riken-Shah** [comment]
Hey @dvishal485, 

I am happy to add these features.
But why aren't we using any parser like cheerio to parse the HTML? 

It will be very easy to add/update other details.

**Comment by dvishal485** [comment]
> Hey @dvishal485,
> 
> I am happy to add these features. But why aren't we using any parser like cheerio to parse the HTML?
> 
> It will be very easy to add/update other details.

The API is deployed using Cloudflare Worker, and using library like Cheerio will cost a lot of memory which may lead to error in free deployment plan ( Check out : https://community.cloudflare.com/t/parsing-html-with-cheerio-using-too-much-cpu-time/24831 )

Also, the project was made just for fun with minimal information, which didn't really required any library to scrape.

---

The repo can be no doubt build with ease using Cheerio in JS. While using BS4 (Python) will also produce outstanding results with deploying services like Vercel, but rebasing the work is a lot of work.

I intend to rebase the whole API along with better information scrapping with BS4 soon as a college project which will make maintainence and contribuition easy.

**Comment by dvishal485** [comment]
> Hey @dvishal485,
> 
> I am happy to add these features. But why aren't we using any parser like cheerio to parse the HTML?
> 
> It will be very easy to add/update other details.

The API is deployed using Cloudflare Worker, and using library like Cheerio will cost a lot of memory which may lead to error in free deployment plan ( Check out : https://community.cloudflare.com/t/parsing-html-with-cheerio-using-too-much-cpu-time/24831 )

Also, the project was made just for fun with minimal information, which didn't really required any library to scrape.

---

The repo can be no doubt build with ease using Cheerio in JS. While using BS4 (Python) will also produce outstanding results with deploying services like Vercel, but rebasing the work is a lot of work.

I intend to rebase the whole API along with better information scrapping with BS4 soon as a college project which will make maintainence and contribuition easy.

**Comment by dvishal485** [comment]
The project is not maintained regularly. New feature updates may not be available.
