### ISSUE TITLE
API Data Crawling Issue

### ISSUE THREAD

**Issue by denxerect** [dvishal485/flipkart-scraper-api#7]
Hi Vishal,

API is not crawling data for product with variation. Its considering its 1st variation and crawling the data.

Regards,

Shubh

**Comment by dvishal485** [comment]
Pardon me for the late response! Can you elaborate what you mean? I didn't quite understand what is the issue you are facing.

**Comment by dvishal485** [comment]
Due to lack of information and logs of any kind, I am closing this issue.
