### ISSUE TITLE
Empty thumbnail

### ISSUE THREAD

**Issue by EvaTechy** [dvishal485/flipkart-scraper-api#8]
API is giving empty thumbnail for search query
https://flipkart-scraper-api.dvishal485.workers.dev/search/women+wear

**Comment by dvishal485** [comment]
Thank you for reporting the issue. I'll look into it.

**Comment by UtkarshSingh5474** [comment]
+1, The thumbnail for the search request is empty. Please Fix it. I can help too!

**Comment by UtkarshSingh5474** [comment]
I just discovered that the thumbnails are working in product detail requests

**Comment by dvishal485** [comment]
Yes, as far as I know, the product page thumbnail is scraped just fine. Only search page thumbnail is erroneous.
I may take some while to fix this, in meantime if you can fix this issue, create a PR for the same. It would be appreciated.

Look into the source code of the search pages for common products and modify the following files:

https://github.com/dvishal485/flipkart-scraper-api/blob/4b94b7dd066cc802dad53f6abb21c64df04a1d77/API/search.js#L89-L91

https://github.com/dvishal485/flipkart-scraper-api/blob/4b94b7dd066cc802dad53f6abb21c64df04a1d77/API/search.js#L112-L117

Do not preferably use any class names or something which may be dynamic.

**Comment by UtkarshSingh5474** [comment]
Tried a lot but couldn't seem to know what's wrong. :(

**Comment by dvishal485** [comment]
> Tried a lot but couldn't seem to know what's wrong. :(

No worries, I pushed a fix check if that works out.
